baseURL = 'https://clumpspirit.com/'
languageCode = 'en-us'
title = 'Edin Dzilic'
theme = 'mxkrsv'
summaryLength = 40
sectionPagesMenu = "main"

[params]
author = 'Edin Dzilic'
nick = 'clump spirit'
license = 'CC BY-SA 4.0'

[markup]
[markup.highlight]
noClasses=false # Use customized stylesheet
tabWidth = 8

[menu]
[[menu.main]]
identifier = 'tags'
name = 'Tags'
title = 'Tags'
pageref = '/tags'
weight = 1 # Make it appear first
